import type { MetadataRoute } from 'next';
import { SITE_CONFIG } from '@/config/site.config';

/**
 * Web App Manifest — served at /manifest.webmanifest.
 *
 * Gives the platform an installable identity on mobile home screens: brand
 * name, obsidian chrome, and the rasterized monogram icons generated by
 * scripts/generate-brand-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_CONFIG.name} — ${SITE_CONFIG.tagline}`,
    short_name: SITE_CONFIG.name,
    description: SITE_CONFIG.description,
    start_url: '/',
    display: 'standalone',
    background_color: SITE_CONFIG.themeColor,
    theme_color: SITE_CONFIG.themeColor,
    icons: [
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml' },
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
}
